#!/usr/bin/env python3
"""Audit recorded Telegram job posts and update location rules."""

from __future__ import annotations

import argparse
from datetime import date, datetime, timedelta
import json
import os
from pathlib import Path
from typing import Any
from zoneinfo import ZoneInfo

from job_alerts_lib.env import load_env
from job_alerts_lib.location_audit import classify_post

SCRIPT_DIRECTORY = Path(__file__).parent
DATA_DIRECTORY = SCRIPT_DIRECTORY / "data"
POST_LOG_PATH = DATA_DIRECTORY / "posted-jobs.jsonl"
GENERATED_RULES_PATH = SCRIPT_DIRECTORY / "config" / "generated-excluded-location-keywords.txt"
REVIEW_DIRECTORY = DATA_DIRECTORY / "reviews"


def load_posts(path: Path) -> list[dict[str, Any]]:
    posts = []
    try:
        lines = path.read_text().splitlines()
    except FileNotFoundError:
        return posts
    for line_number, raw_line in enumerate(lines, start=1):
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        try:
            posts.append(json.loads(line))
        except json.JSONDecodeError as error:
            raise RuntimeError(f"Invalid JSON on {path}:{line_number}") from error
    return posts


def posts_for_date(
    posts: list[dict[str, Any]], audit_date: date, zone: ZoneInfo
) -> list[dict[str, Any]]:
    selected = []
    for post in posts:
        try:
            posted_at = datetime.fromisoformat(post["postedAt"])
        except (KeyError, TypeError, ValueError):
            continue
        if posted_at.astimezone(zone).date() == audit_date:
            selected.append(post)
    return selected


def existing_rules(path: Path) -> tuple[list[str], set[str]]:
    header = [
        "# High-confidence non-European terms generated by telegram_location_audit.py.",
        "# Review changes before committing them. Entries are matched case-insensitively.",
    ]
    try:
        values = {
            line.strip()
            for line in path.read_text().splitlines()
            if line.strip() and not line.lstrip().startswith("#")
        }
    except FileNotFoundError:
        values = set()
    return header, values


def write_outputs(
    audit_label: str,
    candidates: set[str],
    review_rows: list[tuple[str, str, str]],
    dry_run: bool,
) -> None:
    header, values = existing_rules(GENERATED_RULES_PATH)
    values.update(candidates)
    if dry_run:
        return
    GENERATED_RULES_PATH.write_text(
        "\n".join(header + ([""] if values else []) + sorted(values, key=str.casefold)) + "\n"
    )
    REVIEW_DIRECTORY.mkdir(exist_ok=True)
    review_path = REVIEW_DIRECTORY / f"{audit_label}.txt"
    rows = [
        f"# Telegram location review: {audit_label}",
        "# UNKNOWN_REMOTE is not explicitly worldwide or European.",
        "# UNKNOWN could not be classified safely.",
        "",
    ]
    rows.extend(
        f"{classification}\t{location}\t{title}"
        for classification, location, title in review_rows
    )
    review_path.write_text("\n".join(rows) + "\n")


def clear_post_log(path: Path) -> None:
    path.write_text("# Successful Telegram channel posts, one JSON object per line.\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--date", help="Local audit date in YYYY-MM-DD; defaults to yesterday")
    parser.add_argument("--all", action="store_true", help="Audit every pending recorded post")
    parser.add_argument(
        "--consume",
        action="store_true",
        help="Clear the post log after a successful --all audit",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print without writing files")
    args = parser.parse_args()
    if args.all and args.date:
        parser.error("--all and --date cannot be used together")
    if args.consume and not args.all:
        parser.error("--consume requires --all")
    if args.consume and args.dry_run:
        parser.error("--consume cannot be combined with --dry-run")
    return args


def main() -> None:
    load_env(SCRIPT_DIRECTORY / ".env")
    args = parse_args()
    zone = ZoneInfo(os.environ.get("JOB_ALERTS_TIMEZONE", "Europe/Athens"))
    all_posts = load_posts(POST_LOG_PATH)
    if args.all:
        posts = all_posts
        audit_label = f"pending-through-{datetime.now(zone).date().isoformat()}"
        audit_description = "all pending records"
    else:
        audit_date = (
            date.fromisoformat(args.date)
            if args.date
            else datetime.now(zone).date() - timedelta(days=1)
        )
        posts = posts_for_date(all_posts, audit_date, zone)
        audit_label = audit_date.isoformat()
        audit_description = audit_date.isoformat()

    counts: dict[str, int] = {}
    candidates = set()
    review_rows = []
    for post in posts:
        location = str(post.get("location") or "Location not specified")
        title = str(post.get("title") or "")
        url = str(post.get("url") or "")
        classification, terms = classify_post(location, title, url)
        counts[classification] = counts.get(classification, 0) + 1
        candidates.update(terms)
        if classification.startswith("UNKNOWN"):
            review_rows.append((classification, location, title))
        print(f"{classification:16} {location} | {title}")

    write_outputs(audit_label, candidates, review_rows, args.dry_run)
    if args.consume:
        clear_post_log(POST_LOG_PATH)
    summary = ", ".join(f"{key}={value}" for key, value in sorted(counts.items())) or "none"
    print(
        f"Checked {len(posts)} Telegram posts for {audit_description}: {summary}. "
        f"Generated {len(candidates)} exclusion candidates; {len(review_rows)} need review."
    )
    if args.consume:
        print("Consumed all audited records from data/posted-jobs.jsonl.")


if __name__ == "__main__":
    main()
